name: scaffold_widget
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'
homepage: https://github.com/tmcmaster/scaffold_widget/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  faker:

  flutter_workbench:
    git:
      url: https://github.com/tmcmaster/flutter_workbench.git

#dependency_overrides:
#  flutter_workbench:
#    path: ../..
